### create board
POST http://localhost:8080/board
Content-Type: application/json

{
  "title": "맛집소개",
  "content": "사당 삼겹살 맛집이에요",
  "password" : "pass1234",
  "storeName": "논골",
  "keyword": "맛집",
  "locationX": 123.12,
  "locationY": 238.44,
  "menu": "C:\\dev\\yummyTable\\erd.png",
  "capacity": "20"
}

### delete board
DELETE http://localhost:8080/board
Content-Type: application/json

{
  "boardId": 1,
  "password": "pass1234"
}


### get board
GET http://localhost:8080/board/1
Content-Type: application/json
