### create board
POST http://localhost:8080/boards?memberId=1
Content-Type: application/json

{
  "storeId": 2,
  "title": "같이가요",
  "content": "맛집이에요",
  "keyword": "맛집",
  "password" : "pass1234"
}


### delete board
DELETE http://localhost:8080/boards?boardId=1&memberId=1
Content-Type: application/json

{
  "password": "pass1234"
}



### get board
GET http://localhost:8080/boards?boardId=1
Content-Type: application/json


### update board
PATCH http://localhost:8080/boards?boardId=1&memberId=1
Content-Type: application/json

{
  "title": "돈까스 맛집 가여!!!!!",
  "content": "쫀맛탱 돈까스",
  "keyword": "맛집",
  "password": "pass1234"
}