
### create booking
POST http://localhost:8080/booking?storeId=1&memberId=2
Content-Type: application/json

{
  "bookingDate": "2023-12-10",
  "numberOfApplicants": 5
}



### get booking
GET http://localhost:8080/booking?storeId=1
Content-Type: application/json

{
  "bookingDate": "2023-12-09"
}


### delete booking
DELETE http://localhost:8080/booking?storeId=1&bookingId=1
Content-Type: application/json

{
  "bookingDate": "2023-12-10",
  "numberOfApplicants": 5
}


### update booking
PATCH http://localhost:8080/booking?storeId=1&bookingId=1
Content-Type: application/json

{
  "bookingDate": "2023-12-03",
  "numberOfApplicants": 1,
  "newBookingDate": "2023-12-03",
  "newNumberOfApplicants": 3
}


