
### create booking
POST http://localhost:8080/booking?storeId=1
Content-Type: application/json

{
  "bookingDate": "2023-12-03",
  "numberOfApplicants": 3
}


### delete booking
DELETE http://localhost:8080/booking?storeId=1&bookingId=2
Content-Type: application/json

{
  "bookingDate": "2023-12-03",
  "numberOfApplicants": 1
}


### get board
GET http://localhost:8080/board/1
Content-Type: application/json


### update booking
PATCH http://localhost:8080/booking?storeId=1&bookingId=1
Content-Type: application/json

{
  "bookingDate": "2023-12-03",
  "numberOfApplicants": 1,
  "newBookingDate": "2023-12-03",
  "newNumberOfApplicants": 3
}