
### create favorit
POST http://localhost:8080/favorit/1/2
Content-Type: application/json


### delete favorit
DELETE http://localhost:8080/favorit/1/1
Content-Type: application/json



### get favorit
GET http://localhost:8080/favorit/1
Content-Type: application/json

