
### create favorit
POST http://localhost:8080/favorits?storeId=1&memberId=1
Content-Type: application/json


### delete favorit
DELETE http://localhost:8080/favorits?storeId=1&memberId=1
Content-Type: application/json



### get favorit
GET http://localhost:8080/favorits?storeId=1
Content-Type: application/json

