### create member
POST http://localhost:8080/signup
Content-Type: application/json

{
  "password" : "234545",
  "email": "bbbb@gmail.com",
  "username": "사당친구"
}


### signin
PATCH http://localhost:8080/signin
Content-Type: application/json

{
  "password" : "234545",
  "email": "bbbb@gmail.com"
}


### delete member
DELETE http://localhost:8080/member
Content-Type: application/json

{
  "password" : "234545",
  "email": "bbbb@gmail.com"
}



### get member
GET http://localhost:8080/member?memberId=1
Content-Type: application/json


### update member
PATCH http://localhost:8080/member
Content-Type: application/json

{
  "password" : "234545",
  "email": "bbbb@gmail.com",
  "newPassword": "99999"
}