### create member
POST http://localhost:8080/member
Content-Type: application/json

{
  "password" : "pass1234",
  "email": "bbbbb@gmail.com"
}


### delete member
DELETE http://localhost:8080/member
Content-Type: application/json

{
  "password" : "pass1234",
  "email": "bbbbb@gmail.com"
}



### get member
GET http://localhost:8080/member/1
Content-Type: application/json


### update member
PATCH http://localhost:8080/member
Content-Type: application/json

{
  "password" : "pass1234",
  "email": "bbbbb@gmail.com",
  "newPassword": "99999"
}