
### get searchByKeyword
GET http://localhost:8080/searches?page=1&size=5&keyword=맛집
Content-Type: application/json

### get searchByStorename
GET http://localhost:8080/searches/storeName?storeName=초밥
Content-Type: application/json
