
### create store
POST http://localhost:8080/store
Content-Type: application/json

{
  "memberId" : 1,
  "storeName": "맛있다돈까스",
  "keyword": "맛집",
  "locationX": 123.12,
  "locationY": 238.44,
  "menu": "C:\\dev\\yummyTable\\erd.png",
  "capacity": 20

}


### delete store
DELETE http://localhost:8080/store?storeId=1&memberId=1
Content-Type: application/json



### get store
GET http://localhost:8080/store/1
Content-Type: application/json


### update board
PATCH http://localhost:8080/store
Content-Type: application/json

{
  "storeId" : 1,
  "storeName": "맛있다 돈까스 사당점",
  "keyword": "맛집",
  "locationX": 111.11,
  "locationY": 222.22,
  "menu": "C:\\dev\\yummyTable\\erd.png",
  "capacity": 10,
  "memberId" : 1
}