spring:
#  datasource:
#    url: jdbc:h2:mem:test;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yummyTable?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

#  h2:
#    console:
#      enabled: true

  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.test
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

  swagger-ui:
    #path: demo-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    version: v2.0.0
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  paths-to-match: /*